# Base configs
baseurl: "photography"
url: "http://zh1peng.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics:

# UI configs
title: "Zhipeng's Gallery"
subtitle: "See the world through my eyes!"
author: "Ram Patra"
bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  #twitter: "https://www.twitter.com/ramswarooppatra"
  #instagram: "https://www.instagram.com/ramswarooppatra"
  #dribbble: "https://dribbble.com/ramswaroop"
#  linkedin: "https://in.linkedin.com/in/ramswarooppatra"
#  github: "https://www.github.com/ramswaroop"
